const { spawn } = require("node:child_process");
const { EventEmitter } = require("node:events");
const fs = require("node:fs");
const path = require("node:path");

function within(root, candidate) { const relative = path.relative(root, candidate); return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative)); }
function safeJson(file, fallback) { try { return JSON.parse(fs.readFileSync(file, "utf8")); } catch { return fallback; } }
class DapConnection extends EventEmitter {
  constructor(command, args, options = {}) { super(); this.command = command; this.args = args; this.options = options; this.child = null; this.buffer = Buffer.alloc(0); this.sequence = 0; this.pending = new Map(); }
  start() { if (this.child) return; this.child = spawn(this.command, this.args, { cwd: this.options.cwd, env: { ...process.env, ...(this.options.env || {}) }, windowsHide: true, stdio: ["pipe", "pipe", "pipe"] }); this.child.stdout.on("data", chunk => this.consume(chunk)); this.child.stderr.on("data", chunk => this.emit("event", { event: "output", body: { category: "stderr", output: String(chunk) } })); this.child.on("exit", (code, signal) => { for (const item of this.pending.values()) item.reject(new Error(`Debug adapter exited (${code ?? signal}).`)); this.pending.clear(); this.emit("exit", { code, signal }); this.child = null; }); }
  send(message) { const body = Buffer.from(JSON.stringify(message), "utf8"); this.child.stdin.write(`Content-Length: ${body.length}\r\n\r\n`); this.child.stdin.write(body); }
  request(command, args = {}, timeout = 30000) { const seq = ++this.sequence; return new Promise((resolve, reject) => { const timer = setTimeout(() => { this.pending.delete(seq); reject(new Error(`${command} timed out.`)); }, timeout); this.pending.set(seq, { resolve, reject, timer }); this.send({ seq, type: "request", command, arguments: args }); }); }
  consume(chunk) { this.buffer = Buffer.concat([this.buffer, chunk]); while (true) { const boundary = this.buffer.indexOf("\r\n\r\n"); if (boundary < 0) return; const match = this.buffer.subarray(0, boundary).toString("ascii").match(/Content-Length:\s*(\d+)/i); if (!match) { this.buffer = this.buffer.subarray(boundary + 4); continue; } const length = Number(match[1]); if (this.buffer.length < boundary + 4 + length) return; const body = this.buffer.subarray(boundary + 4, boundary + 4 + length); this.buffer = this.buffer.subarray(boundary + 4 + length); this.dispatch(JSON.parse(body.toString("utf8"))); } }
  dispatch(message) { if (message.type === "response") { const item = this.pending.get(message.request_seq); if (!item) return; clearTimeout(item.timer); this.pending.delete(message.request_seq); message.success === false ? item.reject(new Error(message.message || `${message.command} failed.`)) : item.resolve(message.body || {}); } else if (message.type === "event") this.emit("event", message); }
  waitFor(name, timeout = 30000) { return new Promise((resolve, reject) => { const timer = setTimeout(() => { this.off("event", listener); reject(new Error(`Debug adapter did not emit ${name}.`)); }, timeout); const listener = message => { if (message.event !== name) return; clearTimeout(timer); this.off("event", listener); resolve(message.body || {}); }; this.on("event", listener); }); }
  async stop() { const child = this.child; if (!child) return; const exited = new Promise(resolve => child.once("exit", resolve)); try { await this.request("disconnect", { terminateDebuggee: true }, 3000); } catch { child.kill(); } await Promise.race([exited, new Promise(resolve => setTimeout(resolve, 2000))]); if (child.exitCode === null) child.kill(); }
}

class BlueDebugService extends EventEmitter {
  constructor(workspaceRoot, options = {}) { super(); this.root = path.resolve(workspaceRoot); this.moduleRoot = options.moduleRoot || __dirname; this.python = options.python || "python"; this.sessions = new Map(); this.nextId = 0; this.profileFile = path.join(this.root, "Project Blue App", ".blue", "debug", "launch.json"); }
  safePath(value) { const result = path.resolve(this.root, String(value || "")); if (!within(this.root, result)) throw new Error("Debugger paths must stay inside the Project Blue workspace."); return result; }
  adapters() { const debugpy = path.join(this.moduleRoot, "vendor", "python", "debugpy", "adapter"); const node = path.join(this.moduleRoot, "node-debug-adapter.cjs"); return [{ id: "python", installed: fs.existsSync(debugpy), label: "Python (Debugpy 1.8.21)" }, { id: "node", installed: fs.existsSync(node), label: "Node Inspector DAP" }]; }
  profiles() { return safeJson(this.profileFile, { version: 1, configurations: [] }); }
  saveProfile(profile) { const runtime = profile?.runtime; if (!['python', 'node'].includes(runtime)) throw new Error("Debug profile runtime must be python or node."); const program = path.relative(this.root, this.safePath(profile.program)).replace(/\\/g, "/"); const value = { id: String(profile.id || `debug_${Date.now()}`), name: String(profile.name || path.basename(program)).slice(0, 80), request: profile.request === "attach" ? "attach" : "launch", runtime, program, cwd: path.relative(this.root, this.safePath(profile.cwd || this.root)).replace(/\\/g, "/") || ".", args: Array.isArray(profile.args) ? profile.args.map(String).slice(0, 40) : [], webSocketUrl: profile.request === "attach" ? String(profile.webSocketUrl || "") : undefined }; const document = this.profiles(); document.configurations = [...document.configurations.filter(item => item.id !== value.id), value].slice(-50); fs.mkdirSync(path.dirname(this.profileFile), { recursive: true }); fs.writeFileSync(this.profileFile, JSON.stringify(document, null, 2), "utf8"); return value; }
  adapterFor(runtime, cwd) { if (runtime === "python") { const vendor = path.join(this.moduleRoot, "vendor", "python"); return new DapConnection(this.python, ["-m", "debugpy.adapter"], { cwd, env: { PYTHONPATH: vendor } }); } return new DapConnection(process.execPath, [path.join(this.moduleRoot, "node-debug-adapter.cjs")], { cwd, env: { ELECTRON_RUN_AS_NODE: "1" } }); }
  async start(value) { const runtime = value.runtime; if (!['python', 'node'].includes(runtime)) throw new Error("Choose Python or Node debugging."); const request = value.request === "attach" ? "attach" : "launch"; const program = request === "launch" ? this.safePath(value.program) : undefined; const cwd = this.safePath(value.cwd || (program ? path.dirname(program) : this.root)); const connection = this.adapterFor(runtime, cwd); connection.start(); const id = `debug-${++this.nextId}`; const session = { id, runtime, request, program, cwd, connection, state: "starting", breakpoints: new Map(), stopped: null, output: [] }; this.sessions.set(id, session); connection.on("event", message => { if (message.event === "stopped") { session.state = "stopped"; session.stopped = message.body; } else if (message.event === "continued") session.state = "running"; else if (["terminated", "exited"].includes(message.event)) session.state = "ended"; else if (message.event === "output") { session.output.push(message.body); if (session.output.length > 500) session.output.splice(0, session.output.length - 500); } this.emit("event", { sessionId: id, ...message }); }); connection.on("exit", data => { session.state = "ended"; this.emit("event", { sessionId: id, event: "adapterExit", body: data }); }); await connection.request("initialize", { clientID: "project-blue", clientName: "Project Blue", adapterID: runtime, pathFormat: "path", linesStartAt1: true, columnsStartAt1: true, supportsVariableType: true, supportsRunInTerminalRequest: false }); const initialized = connection.waitFor("initialized"); const launchArgs = request === "launch" ? { name: value.name || path.basename(program), type: runtime === "python" ? "python" : "node", request, program, cwd, args: Array.isArray(value.args) ? value.args : [], console: "internalConsole", stopOnEntry: value.stopOnEntry !== false, justMyCode: true } : { request, connect: value.connect, webSocketUrl: value.webSocketUrl }; const launch = connection.request(request, launchArgs, 60000); await initialized; for (const [source, points] of Object.entries(value.breakpoints || {})) await this.setBreakpoints(id, { source, breakpoints: points }); await connection.request("configurationDone", {}); await launch; session.state = "running"; return this.describe(session); }
  session(id) { const value = this.sessions.get(id); if (!value) throw new Error("Debug session not found."); return value; }
  describe(session) { return { id: session.id, runtime: session.runtime, request: session.request, program: session.program, cwd: session.cwd, state: session.state, stopped: session.stopped, output: session.output.slice(-100) }; }
  list() { return [...this.sessions.values()].map(value => this.describe(value)); }
  async setBreakpoints(id, value) { const session = this.session(id); const source = this.safePath(value.source); const breakpoints = (value.breakpoints || []).map(item => ({ line: Math.max(1, Number(item.line) || 1), condition: String(item.condition || "").trim() || undefined })); const result = await session.connection.request("setBreakpoints", { source: { name: path.basename(source), path: source }, breakpoints, lines: breakpoints.map(item => item.line), sourceModified: false }); session.breakpoints.set(source, breakpoints); return result.breakpoints || []; }
  async command(id, command, args = {}) { const session = this.session(id); const allowed = { continue: "continue", pause: "pause", next: "next", stepIn: "stepIn", stepOut: "stepOut", threads: "threads", stackTrace: "stackTrace", scopes: "scopes", variables: "variables", evaluate: "evaluate" }; if (!allowed[command]) throw new Error("Unsupported debugger command."); return session.connection.request(allowed[command], { threadId: 1, ...args }); }
  async stop(id) { const session = this.session(id); await session.connection.stop(); session.state = "ended"; return this.describe(session); }
  async stopAll() { await Promise.all([...this.sessions.values()].filter(item => item.state !== "ended").map(item => item.connection.stop())); }
  status() { return { adapters: this.adapters(), sessions: this.list(), profiles: this.profiles().configurations }; }
}
module.exports = { BlueDebugService, DapConnection };
